var arr1 = [1, 2, 3, 4];
var arr2 = [1, 2, 3, 4];
var arr3 = ['sad', 'sdg', 'sg'];
var arr4 = ['sad', 'sdg', 'sg'];
var arr5 = [true, false];
var arr6 = [true, false];
var arr7 = ['a', 1, false];
var arr8 = ['a', 1, false];
var arr9 = ['sdf', 5];
var arr10 = [5, 'sdf'];
//# sourceMappingURL=lab2.js.map